version: '3.8'

services:
  falah-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: falah-bot
    ports:
      - "8501:8501"
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
