[zerodha]
api_key = "ijzeuwuylr3g0kug"
api_secret = "yy1wd2wn8r0wx4mus00vxllgss03nuqx"
access_token = "NzJyo465T8nzBxAkmxu4jmhxPxC1OrG2"

[telegram]
bot_token = "7763450358:AAH32bWYyu_hXR6l-UaVMaarFGZ4YFOv6q8"
chat_id = "6784139148"

[sheets]
creds_file = "falah-credentials.json"
spreadsheet_key = "1ccAxmGmqHoSAj9vFiZIGuV2wM6KIfnRdSebfgx1Cy_c"
